version: '3.8'

services:
  flask:
    build:
      context: ./flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  svelte:
    build:
      context: ./svelte-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./svelte-app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
      - svelte
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge
