version: '3.8'

services:
  flask:
    build:
      context: ./flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://proxy:9000/0
    depends_on:
      - haproxy
    networks:
      - app-network

  svelte:
    build:
      context: ./svelte-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./svelte-app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
      - svelte
    networks:
      - app-network

  redis01:
    build: ./redis
    ports:
      - 6379:6379
    networks:
      - host
    env_file:
      - './redis/env/master_variables.env'
    networks:
      - app-network

  redis02:
    build: ./redis
    ports:
      - 6380:6379
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'
    networks:
      - app-network

  redis03:
    build: ./redis
    ports:
      - 6381:6379
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'
    networks:
      - app-network

  proxy:
    build: ./haproxy
    depends_on:
      - redis01
      - redis02
      - redis03
    networks:
      - host
    ports:
      - '9000:9000'
      - '8080:80'

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:

networks:
  host:
  app-network:
    driver: bridge