version: '3.8'

services:
  flask:
    build:
      context: ./flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://haproxy:6379/0
    depends_on:
      - haproxy
    networks:
      - app-network

  svelte:
    build:
      context: ./svelte-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./svelte-app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
      - svelte
    networks:
      - app-network

  redis1:
    image: "redis:6.2-alpine"
    command: redis-server --appendonly yes --port 6379
    volumes:
      - redis-data-1:/data
    networks:
      - app-network

  redis2:
    image: "redis:6.2-alpine"
    command: redis-server --appendonly yes --port 6380
    volumes:
      - redis-data-2:/data
    networks:
      - app-network

  redis3:
    image: "redis:6.2-alpine"
    command: redis-server --appendonly yes --port 6381
    volumes:
      - redis-data-3:/data
    networks:
      - app-network

  haproxy:
    image: haproxy:2.3
    hostname: haproxy
    ports:
      - "6379:6379"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - app-network

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:

networks:
  app-network:
    driver: bridge