version: '3.8'

services:
  flask:
    build:
      context: ./flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://haproxy:6379/0
    networks:
      - app-network

  svelte:
    build:
      context: ./svelte-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./svelte-app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
      - svelte
    networks:
      - app-network

  redis-master:
    image: redis:6.0.7
    container_name: redis-master
    restart: always
    volumes:
      - redis_master:/data
    ports:
      - 6379:6379
    networks:
      - app-network

  redis-slave:
    image: redis:6.0.7
    container_name: redis-slave
    restart: always
    volumes:
      - redis_slave:/data
    ports:
      - 6479:6379
    command: redis-server --slaveof redis-master 6379
    networks:
      - app-network

volumes:
  redis_master:
  redis_slave:

networks:
  app-network:
    driver: bridge