version: '3.8'

services:
  flask:
    build:
      context: ./flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis-main:6379/0
    depends_on:
      - redis-main
    networks:
      - app-network

  svelte:
    build:
      context: ./svelte-app
      args:
        - SERVER_URL=${SERVER_URL}
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=${SERVER_URL}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./svelte-app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
      - svelte
    networks:
      - app-network

  redis-main:
    image: redis:6.0.7
    container_name: redis-main
    restart: always
    volumes:
      - redis_main:/data
    ports:
      - 6379:6379
    networks:
      - app-network

  redis-secondary:
    image: redis:6.0.7
    container_name: redis-secondary
    restart: always
    volumes:
      - redis_secondary:/data
    ports:
      - 6479:6379
    command: redis-server --slaveof redis-main 6379
    networks:
      - app-network

volumes:
  redis_main:
  redis_secondary:

networks:
  app-network:
    driver: bridge