version: '3.8'

services:
  flask:
    build:
      context: ./flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    environment:
      - FLASK_ENV=production

  svelte:
    build:
      context: ./svelte-app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./svelte-app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
      - svelte
