# Svelte Dockerfile
FROM node:18

WORKDIR /app

COPY svelte-app/package.json svelte-app/package-lock.json ./
RUN npm install

COPY svelte-app/ .

RUN npm run build

EXPOSE 80
CMD ["npx", "serve", "public"]
