version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
      - .env.${FLASK_ENV:-development}
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
    command: run